[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "hte-workflow"
version = "0.0.0"
dependencies = ["pandas", "numpy", "openpyxl", "matplotlib"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}
